### ISSUE TITLE
front end cannot local start, import dtstack PW

### ISSUE THREAD

**Issue by Jixiangup** [DTStack/chengying-front#1]
![image](https://user-images.githubusercontent.com/75556346/170973417-002b7771-c424-4150-aa42-0c512b12fcf8.png)

local system os for windows 
yarn version `1.22.17`
node version `v16.15.0`

**Comment by wewoor** [comment]
yarn.lock 中的镜像地址是我们内部的镜像服务，你可以手动指定下npm镜像地址，或者把 yarn.lock 删掉安装试试 @bnyte

**Comment by Jixiangup** [comment]
> yarn.lock 中的镜像地址是我们内部的镜像服务，你可以手动指定下npm镜像地址，或者把 yarn.lock 删掉安装试试 @bnyte

好的我试一下，这个位置应该将yarn.loak配置一下`.gitignore`比较好吧

**Comment by Jixiangup** [comment]
![image](https://user-images.githubusercontent.com/75556346/170979581-09461181-22bc-41c1-ae17-2d9321bf65d5.png)
依赖下载成功，启动依然报错

**Comment by violet-panpan** [comment]
少了babelrc文件已经补上了

**Comment by Jixiangup** [comment]
> 少了babelrc文件已经补上了

好的我有空了看看，先关闭这个issue 有问题我在打开
